# **PYTORCH COURSE BY DANEIL BOURKE**

**Creating a range of tensors**

In [2]:
import torch 
scalar = torch.tensor(7)
print(scalar)
scalar.item()
vector = torch.tensor([1,2])
vector.ndim

tensor(7)


1

# **THE DIFFERENCE BETWEEN SHAPE , SIZE , NDIM**

The difference between shape , size is that size is a function (required () to execute) and shape is an attribute that is it can be executed directly this is the only difference between shape and size else the outputs of both of them is same


In [21]:
matrix = torch.tensor(([1,2,0],[5,6,7],[87,89,2348950]))
print(matrix.size())
print(matrix.shape)

torch.Size([3, 3])
torch.Size([3, 3])


# **RANDOM TENSORS**

Why random tensors?

Random tensors are important because the way many neural netwoks learn is that they start with tensors fill of random numvers and then those random numvers to better represent the data.

# **Start with random numbers -> Look at data -> update random number -> look at data -> update random numbers**

In [ ]:
#Create a random tensor of size (3,4)
random = torch.rand([3,4])
random

In [8]:
#Create a random tensor to store an image 
random_image = torch.rand(size = (244,244,3))
random_image.ndim , random_image.shape

(3, torch.Size([244, 244, 3]))

**Zeros and ones**

In [6]:
#Create a tensor of all zeros
zero = torch.zeros(size=(3,3))
#Creating a tensor of all ones
one = torch.ones(size= (3,3))
#torch.zeros_like() creates a new tensor of all zeros with the same shape, dtype, and device as another tensor.
y = torch.zeros_like(input = one)
y 



tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**Tensor data - types**

In [10]:
float_32 = torch.tensor((3.0,6.0,9.0),dtype = None)
float_31 = torch.tensor((3.0,6.0,9.0),dtype = torch.float16 ) 
float_32.dtype , float_31.dtype , float_32.device

(torch.float32, torch.float16, device(type='cpu'))

**Tensor data type is one of three big error thatyou will rin into with PyTorch & deep learning :**

1.) Tensors not the right datatype (SOME OPERATIONS) : use tensor.dtype

2.) Tensors not the right shape : use tensors.shape

3,) Tensors not on the right device : use tensor.device

In [13]:
float_16 = float_32.type(torch.float16)
float_16.device

device(type='cpu')

# Manipulating Tensors (tensor operations)

* Addition 

* Subtraction 

* Multiplications 

* Division

### **Two main ways of controlling tensors in nueral networks is by using either element wise multiplication or matrx multiplication**

In [ ]:
tensor = torch.tensor([1,2,3])
tensor1 = torch.tensor(([7,8] , [9 , 10] , [11,12]))
tensor
torch.mul(tensor , 10)          #Multiplication
torch.add(tensor , 10)          #Addition
torch.subtract(tensor , 10)     #Subtraction
torch.matmul(tensor , tensor1)  #Matrix Multiplication

tensor([58, 64])

# Rules for matrix multiplication

**1.) The inner dimensions must match :**
* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

**2.) The resulting matrix has the shape of the outer dimensions :**

* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)

**To fix the shape issues we can manupulate the shape of one of our tensors using a transpose.**

**A transpose switches the axes or dimensions of a given tensor.**

In [9]:
tens = torch.tensor(([1,2,3] , 
                     [4,5,6] , 
                     [7,8,9]))
torch.matmul(tens , tens.T)

tensor([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]])

# Finding the min , max , mean , sum , argmin (position of minimum) , argmax(position of maximum) etc (tensor aggregation)

In [41]:
ten = torch.tensor(([1,2] , [3,4]))
ten.min() , ten.max() , ten.dtype
ten.type(torch.float32).mean()

tensor(2.5000)

# NOTE :

**torch.mean() function requires a tensor of float32 datatype to work**